### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './filter/filter.json'

### ISSUE THREAD

**Issue by myraspxbmc** [SCP002/m3u-gen-acestream#2]
Started at Nov 24 17:50:55

Internet connection is up.

Processing data set 1 of 1
Traceback (most recent call last):
  File "./src/m3u_gen_acestream.py", line 53, in <module>
    M3UGenAceStream.main()
  File "./src/m3u_gen_acestream.py", line 33, in main
    channel_handler.data_set = data_set
  File "/src/channel/channel_handler.py", line 37, in data_set
    self._filter_handler.data_set = data_set
  File "/src/filter/filter_handler.py", line 33, in data_set
    with closing(open(filter_file_name, 'r', filter_file_encoding)) as filter_file:
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)

**Comment by SCP002** [comment]
Hello.

Can't test this issue right now, but will have time tomorrow.

Meanwhile, seems it can't find filter file.
Have a feeling this issue is related to relative path and current directory which app starts from.
So, you can try following:

* Download:
  https://github.com/SCP002/m3u-gen-acestream/archive/master.zip
* Extract archive.
* In console:
  `cd m3u-gen-acestream-master`
  `cd src`
  `py m3u_gen_acestream.py`

Check if everything okay.
If so, see output file at `m3u-gen-acestream-master/out/`.

If anything get's wrong, feel free to ask here. Thanks! 😄

**Comment by SCP002** [comment]
Closed with https://github.com/SCP002/m3u-gen-acestream/commit/cde1b398cac235b42f11d84e9f85e190d7d47dd0.
